# Generated by Django 3.0.5 on 2023-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('Module1', 'Module1')], default='Module1', max_length=10),
        ),
    ]
