# Generated by Django 3.0.5 on 2023-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20231023_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='course',
            field=models.CharField(choices=[('IT', 'IT'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical')], default='IT', max_length=10),
        ),
    ]
