# Generated by Django 3.0.5 on 2023-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_studentextra_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='national_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='parent_mobile',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='parent_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
