# Generated by Django 3.0.5 on 2023-10-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20231027_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
