# Generated by Django 3.0.5 on 2023-10-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_studentextra_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='leaving_cert_scan',
            field=models.FileField(blank=True, help_text='Upload a scan of your leaving certificate as a PDF file.', null=True, upload_to='pdf_files/'),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='national_id_scan',
            field=models.FileField(blank=True, help_text='Upload a scan of your national ID as a PDF file.', null=True, upload_to='pdf_files/'),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='result_slip',
            field=models.FileField(blank=True, help_text=' result slip as a PDF file.', null=True, upload_to='pdf_files/'),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
