# Generated by Django 3.0.5 on 2023-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20231029_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='programs',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Artisan', 'Artisan')], default='Diploma', max_length=30),
        ),
    ]
