# Generated by Django 3.0.5 on 2023-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_studentextra_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('Module1', 'Module1'), ('Module2', 'Module2'), ('Module3', 'Module3')], default='Module1', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='leaving_cert_scan',
            field=models.FileField(help_text='Upload a scan of your leaving certificate as a PDF file.', null=True, upload_to='pdf_files/'),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='national_id_scan',
            field=models.FileField(help_text='Upload a scan of your national ID as a PDF file.', null=True, upload_to='pdf_files/'),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='school/static/images/'),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='result_slip',
            field=models.FileField(help_text=' result slip as a PDF file.', null=True, upload_to='pdf_files/'),
        ),
    ]
